// 일본어 단어 데이터 (단어, 읽기, 뜻)
const VOCABULARY = [
  { word: "本", reading: "ほん", meaning: "책" },
  { word: "水", reading: "みず", meaning: "물" },
  { word: "人", reading: "ひと", meaning: "사람" },
  { word: "山", reading: "やま", meaning: "산" },
  { word: "川", reading: "かわ", meaning: "강" },
  { word: "木", reading: "き", meaning: "나무" },
  { word: "火", reading: "ひ", meaning: "불" },
  { word: "日", reading: "ひ", meaning: "날, 해" },
  { word: "月", reading: "つき", meaning: "달" },
  { word: "花", reading: "はな", meaning: "꽃" },
  { word: "魚", reading: "さかな", meaning: "생선" },
  { word: "犬", reading: "いぬ", meaning: "개" },
  { word: "猫", reading: "ねこ", meaning: "고양이" },
  { word: "食べる", reading: "たべる", meaning: "먹다" },
  { word: "飲む", reading: "のむ", meaning: "마시다" },
  { word: "行く", reading: "いく", meaning: "가다" },
  { word: "来る", reading: "くる", meaning: "오다" },
  { word: "見る", reading: "みる", meaning: "보다" },
  { word: "聞く", reading: "きく", meaning: "듣다" },
  { word: "読む", reading: "よむ", meaning: "읽다" },
  { word: "書く", reading: "かく", meaning: "쓰다" },
  { word: "話す", reading: "はなす", meaning: "말하다" },
  { word: "勉強", reading: "べんきょう", meaning: "공부" },
  { word: "学校", reading: "がっこう", meaning: "학교" },
  { word: "友達", reading: "ともだち", meaning: "친구" },
  { word: "家族", reading: "かぞく", meaning: "가족" },
  { word: "朝", reading: "あさ", meaning: "아침" },
  { word: "夜", reading: "よる", meaning: "밤" },
  { word: "今日", reading: "きょう", meaning: "오늘" },
  { word: "明日", reading: "あした", meaning: "내일" },
  { word: "元気", reading: "げんき", meaning: "건강, 활기찬" },
  { word: "好き", reading: "すき", meaning: "좋아함" },
  { word: "大きい", reading: "おおきい", meaning: "크다" },
  { word: "小さい", reading: "ちいさい", meaning: "작다" },
  { word: "新しい", reading: "あたらしい", meaning: "새로운" },
  { word: "暑い", reading: "あつい", meaning: "덥다" },
  { word: "寒い", reading: "さむい", meaning: "춥다" },
  { word: "ありがとう", reading: "ありがとう", meaning: "감사합니다" },
  { word: "すみません", reading: "すみません", meaning: "죄송합니다" },
  { word: "おはよう", reading: "おはよう", meaning: "좋은 아침" },
  { word: "こんにちは", reading: "こんにちは", meaning: "안녕하세요" },
  { word: "さようなら", reading: "さようなら", meaning: "안녕히 가세요" },
];
